# Generated by Django 5.1.2 on 2024-12-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0002_motorcycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorcycle',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
