# Generated by Django 5.1.2 on 2024-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_rename_brand_name_motorcycle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
