# Generated by Django 5.1.2 on 2025-01-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0004_car_date_added_motorcycle_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='fuel_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
